In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
x = iris.data
y = iris.target.reshape(-1,1)
print(x)
print(y)

encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y)
print(y_encoded)

x_tr, x_ts, y_tr, y_ts = train_test_split(x,y_encoded,test_size=0.2,random_state=42)
x_tr_nn,x_ts_nn,y_tr_nn,y_ts_nn = train_test_split(x,y_encoded, test_size=0.2, random_state=42) ## nn "neural network"

# Machine Learning Approach, Decision Tree Classifier
tree_model = DecisionTreeClassifier()
tree_model.fit(x_tr,y_tr)
y_pred_tree = tree_model.predict(x_ts)
tree_accuracy = accuracy_score(y_ts, y_pred_tree)
print("Decision Tree Accuracy (ML):", tree_accuracy)
# Deep Learning Approach, Neural Network
nn_model = Sequential([
    Dense(16, activation="relu", input_shape=(4,)),
    Dense(16, activation="relu"),
    Dense(3,  activation="softmax")
])

nn_model.compile(optimizer="adam",
                 loss="categorical_crossentropy",
                 metrics=["accuracy"])

nn_model.fit(x_tr_nn,y_tr_nn,epochs=50,batch_size=5,validation_split=0.1,verbose=1)

nn_lose, nn_accuracy = nn_model.evaluate(x_ts_nn, y_ts_nn, verbose=1)

print("Neural Network Accuracy (DL):", nn_accuracy)

#Compare
print("Comparison of ML and DL Approaches:")
print("Decision Tree Accuracy (ML):", tree_accuracy)
print("Neural Network Accuracy (DL):", nn_accuracy)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

c:\Users\flori\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5185 - loss: 1.0806 - val_accuracy: 0.5833 - val_loss: 0.9778
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6667 - loss: 0.8572 - val_accuracy: 0.5833 - val_loss: 0.8503
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6667 - loss: 0.7682 - val_accuracy: 0.5833 - val_loss: 0.7644
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6759 - loss: 0.7063 - val_accuracy: 0.5833 - val_loss: 0.7099
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6852 - loss: 0.6498 - val_accuracy: 0.7500 - val_loss: 0.6640
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8889 - loss: 0.6037 - val_accuracy: 1.0000 - val_loss: 0.6230
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7593 - loss: 0.5604 - val_accuracy: 0.7500 - val_loss: 0.5896
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8611 - loss: 0.5213 - val_accuracy: 1.0000 - val_loss: 0.5529
Epo